linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gochecknoinits
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

# don't enable:
#    - asciicheck
#    - exhaustive
#    - funlen
#    - gochecknoglobals
#    - gocognit
#    - goconst
#    - gocyclo
#    - godot
#    - godox
#    - goerr113
#    - golint
#    - gomnd
#    - interfacer
#    - lll
#    - maligned
#    - nestif
#    - prealloc
#    - stylecheck
#    - testpackage
